Added test id for menu
neetozone/neeto-editor pull request #1024
Opened 2024-03-07 08:44 UTC by sreehari2003

- Fixes #1015 

**Description**

**Checklist**

- [ ] I have made corresponding changes to the documentation.
- [ ] I have updated the types definition of modified exports.
- [ ] I have verified the functionality in some of the neeto web-apps.
- [ ] I have added the necessary label (patch/minor/major - If package publish
      is required).
      
      
      
<img width="1121" alt="Screenshot 2024-03-07 at 2 09 47 PM" src="https://github.com/bigbinary/neeto-editor/assets/66205494/637aec1c-ce72-4ff6-bd05-d06858280dc0">

I have added data cy labels for all the menu buttons

**Reviewers**

2024-03-08 14:33 UTC, VarunSriram99 requested changes
@sreehari2003 A few questions,

**Questions**
- Why are we going through all these steps for adding a data-cy label? Button has option for other props. So just add the "data-cy" label in the buttonProps?
- Why are we adding a data-test-id label when we use data-cy labels in our tests?
- Even if you're adding a test-id, it should `data-testid` and not `data-test-id`
- Why are we not using the hyphenize utlity from neetoCist?

2024-03-09 15:13 UTC, sreehari2003 commented
> @sreehari2003 A few questions,
> 
> **Questions**
> 
> * Why are we going through all these steps for adding a data-cy label? Button has option for other props. So just add the "data-cy" label in the buttonProps?
> * Why are we adding a data-test-id label when we use data-cy labels in our tests?
> * Even if you're adding a test-id, it should `data-testid` and not `data-test-id`
> * Why are we not using the hyphenize utlity from neetoCist?

<img width="1038" alt="Screenshot 2024-03-09 at 8 41 47 PM" src="https://github.com/bigbinary/neeto-editor/assets/66205494/04442d44-21e2-4d77-a2da-1a33099bdba3">

hyphenate is not available to import

2024-03-11 10:01 UTC, VarunSriram99 requested changes
@sreehari2003 _a Please make sure you're taking care of all the review suggestions before re-assigning.

2024-03-11 10:01 UTC, VarunSriram99 commented on src/components/Editor/Menu/Headless/Option/index.jsx
> +      data-cy={optionName.replace(/\s+/g, "-")}
Use [hyphenate from neeto-cist ](https://github.com/bigbinary/neeto-cist/blob/main/docs/pure/strings.md#hyphenate).

2024-03-11 10:04 UTC, VarunSriram99 commented
> > @sreehari2003 A few questions,
> > **Questions**
> > 
> > * Why are we going through all these steps for adding a data-cy label? Button has option for other props. So just add the "data-cy" label in the buttonProps?
> > * Why are we adding a data-test-id label when we use data-cy labels in our tests?
> > * Even if you're adding a test-id, it should `data-testid` and not `data-test-id`
> > * Why are we not using the hyphenize utlity from neetoCist?
> 
> <img alt="Screenshot 2024-03-09 at 8 41 47 PM" width="1038" src="https://private-user-images.githubusercontent.com/66205494/311446159-04442d44-21e2-4d77-a2da-1a33099bdba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE2MDYsIm5iZiI6MTcxMDE1MTMwNiwicGF0aCI6Ii82NjIwNTQ5NC8zMTE0NDYxNTktMDQ0NDJkNDQtMjFlMi00ZDc3LWEyZGEtMWEzMzA5OWJkYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYTZjNmU5MmM3MTNhN2RmZmQ2ZGRhZTE3MWIwMDQyZjQ5NWU4YzZiOGFjODQwODU1M2FmNjhjM2VkNWM5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FyiBzXqq2RYPEWuq9JsIlWqaisQGThFuTQIbJ6aTk7M">
> hyphenate is not available to import

@sreehari2003 its hyphenate. Please go through all the neeto-cist and Playwright commons utilities carefully to make sure we're not repeating the logic.

2024-03-13 14:50 UTC, sreehari2003 commented
- This Issue needs to be fixed first  #1027

2024-03-19 14:38 UTC, VarunSriram99 approved these changes
@sreehari2003 _a LGTM

2024-03-21 08:08 UTC, merged