Updated mentions search logic
neetozone/neeto-editor pull request #104
Opened 2021-12-23 12:15 UTC by AbhayVAshokan

Fixes #102
- Moved the position of the color picker in the fixed menu.
- Alphabetically sorted all mentions.
- Updated filter logic to use "substring" instead of "startsWith".
- Added the message "no results" if the mentions query does not match anyone.
- Removed limit 5 from mentions logic, added a fixed width and height to mentions popup with overflow scroll.
- Added scroll handler for mentions popup (ref #82). Extracted the logic to a separate file.

Demo: https://vimeo.com/659636934/76ba15c94b

@amaldinesh7 _a please review.
cc: @labeebklatif

2021-12-24 06:51 UTC, amaldinesh7 commented
@AbhayVAshokan _a Please check this video https://vimeo.com/659865181/8e90ce7daa

2021-12-24 07:01 UTC, amaldinesh7 requested changes
@AbhayVAshokan I've added one comment. Please take a look.

2021-12-24 07:06 UTC, AbhayVAshokan commented on lib/components/Editor/CustomExtensions/useCustomExtensions.js
> +                const name1 = mention1.label || mention1;
@amaldinesh7 `mention1` is either an `object` or a `string`.
```js
[
  {
    label: "Oliver Smith",
    key: "oliver-smith",
    imageUrl: "https://i.pravatar.cc/300",
  },
  "Jaden Smith",
]
```

If the above approach is confusing, I can change it to `if (typeof mention1 === "string") { ...`.

2021-12-26 18:30 UTC, amaldinesh7 commented on lib/components/Editor/CustomExtensions/useCustomExtensions.js
> +                const name1 = mention1.label || mention1;
Yes. Please do explicitly specify either of the condition.

2021-12-27 02:43 UTC, AbhayVAshokan commented
@amaldinesh7 _a please look at the new changes.

2021-12-27 11:42 UTC, amaldinesh7 commented
@AbhayVAshokan _a The issue mentioned in the video still persists. Did you look into that issue?

2021-12-27 11:48 UTC, AbhayVAshokan commented
Oops. Let me take a look.

2021-12-27 12:47 UTC, AbhayVAshokan commented
@amaldinesh7 _a please have a look at the changes. It was an issue specific to Chrome.
![Mentions separator new line](https://user-images.githubusercontent.com/35297280/147473030-52888691-a0f3-4ef7-b983-bb9c79a7be36.gif)

2021-12-27 17:50 UTC, amaldinesh7 commented
LGTM!

2021-12-27 17:51 UTC, merged