Added option to choose if a link should open in new tab
neetozone/neeto-editor pull request #1085
Opened 2024-05-05 08:58 UTC by gaagul

- Fixes #1081 

**Description**

- Added: option to choose if a link should open in new tab

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

2024-05-05 08:59 UTC, gaagul commented
@AbhayVAshokan Please let me know if the are any updates needed to the changes.

2024-05-06 08:33 UTC, AbhayVAshokan requested changes
@gaagul _a: https://abhay-ashokan.neetorecord.com/watch/1594d856-27f7-4588-b480-ad74907ce98a

2024-05-06 08:33 UTC, AbhayVAshokan commented on src/components/Editor/LinkPopOver.jsx
> +          />
Use a `Checkbox` instead of a `Switch`.

2024-05-06 11:26 UTC, gaagul commented
@AbhayVAshokan _a Please have a look at the updates.

2024-05-08 10:36 UTC, AbhayVAshokan approved these changes

2024-05-08 10:37 UTC, merged