Improved mentions UI
neetozone/neeto-editor pull request #1128
Opened 2024-05-31 18:21 UTC by praveen-murali-ind

- Fixes #1115 

- The interface has been updated to light mode.
- Made it similar to the mentions UI in the editor menu.

After
<img width="561" alt="Screenshot 2024-05-31 at 11 49 26 PM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/cb69015a-a103-4257-9124-597b0e874cb5">
<img width="557" alt="Screenshot 2024-05-31 at 11 50 35 PM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/6467883f-cfe0-43db-a892-9bd971edc421">

Before
<img width="550" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/8749438/578e78ea-1fa7-4465-80fa-55fd6d7ea7dd">

**Description**

**Checklist**

- [ ] I have made corresponding changes to the documentation.
- [ ] I have updated the types definition of modified exports.
- [ ] I have verified the functionality in some of the neeto web-apps.
- [ ] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

2024-05-31 18:22 UTC, praveen-murali-ind commented
@AbhayVAshokan _a Please check.

cc @deepakjosp

2024-06-02 18:54 UTC, AbhayVAshokan requested changes
@praveen-murali-ind _a

The options are navigable by keyboard. Can you please update the styles so that it would be possible?

**Before vs After**

<div style="display: flex;">
  <img src="https://github.com/bigbinary/neeto-editor/assets/35297280/5e764433-13bc-455c-92fb-e20acd98b7cd" width="45%" />
  <img src="https://github.com/bigbinary/neeto-editor/assets/35297280/7db3b1b2-265c-480b-8878-1ad95300feef" width="45%" />
</div>

2024-06-05 09:37 UTC, praveen-murali-ind commented
@AbhayVAshokan The options are already keyboard accessible, as I'm using NeetoUI Dropdown sub-components which are themselves keyboard friendly.


https://github.com/bigbinary/neeto-editor/assets/48869249/6961cc28-c939-4013-b4eb-d9e65ff15b99

2024-06-05 12:04 UTC, AbhayVAshokan approved these changes

2024-06-05 12:13 UTC, merged