Code cleanup
neetozone/neeto-editor pull request #191
Opened 2022-03-04 14:10 UTC by labeebklatif

Fixes #150 

@karthiknmenon _a Please review the changes

2022-03-06 02:11 UTC, karthiknmenon requested changes
@labeebklatif _a Few minor suggestions. Please check.

2022-03-06 02:11 UTC, karthiknmenon commented on lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
>          description: "Add a plain text block",
Can we move the title and descriptions to constants as well? 
Also, please add periods to the end of each sentence in descriptions.

2022-03-06 02:11 UTC, karthiknmenon commented on lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
>  } from "@bigbinary/neeto-icons";
Let's update neetoIcons to the latest version.

2022-03-06 02:11 UTC, karthiknmenon commented on lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
>  import isEmpty from "lodash.isempty";
Can we use ramda instead of lodash at all places in the repo?

2022-03-08 07:19 UTC, labeebklatif commented
@karthiknmenon _A suggested changes done. Please have a look

2022-03-08 07:29 UTC, labeebklatif commented
@labeebklatif _a

2022-03-08 07:34 UTC, labeebklatif commented
@karthiknmenon _A suggested changes done. Please have a look

2022-03-08 08:20 UTC, karthiknmenon approved these changes

2022-03-08 08:20 UTC, merged