Removed controlled mode
neetozone/neeto-editor pull request #193
Opened 2022-03-07 14:38 UTC by AbhayVAshokan

Fixes #192 
Fixes #184 since it is specific to the controlled editor. Works perfectly in uncontrolled mode.

Removed controlled mode from editor. Here are some notable changes.
1. Removed logic added specifically for controlled editor:
1.1. Remove multiple instances of slash commands using `document.querySelector('[id^="tippy"]')`.
1.2. Replacement of blank spaces with `&nbsp;`. 
2. Iframe did not persist when toggled between markdown mode and rich text mode. Updated code to permit `iframe` tags.
3. Class to highlight focussed emoji was deleted during cleanup of styles. Added it back.

Demo: https://vimeo.com/685476970/c2c51dd363

@labeebklatif _a please review.
cc: @karthiknmenon

2022-03-09 08:13 UTC, labeebklatif commented
@AbhayVAshokan _a Please update the documentation  regarding the imperative methods of editor as discussed over chat

2022-03-10 06:14 UTC, AbhayVAshokan commented
@labeebklatif _a please review.

2022-03-10 11:29 UTC, labeebklatif requested changes
Changes looks good. but now that editor is made uncontrolled. we should add support for initialValue which was there earlier before making this controlled. let's bring it back

@AbhayVAshokan _a

2022-03-10 11:50 UTC, AbhayVAshokan commented
@labeebklatif _a please review. I've changed `value` prop to `initialValue`.

- Additionally I made one small improvement (c6668308000c42312db743e17359e811681b6071) which I found today while reading the editor API docs: https://tiptap.dev/api/editor#autofocus.

2022-03-10 12:19 UTC, labeebklatif approved these changes
LGTM

2022-03-10 12:19 UTC, merged