Added error prop
neetozone/neeto-editor pull request #240
Opened 2022-05-20 12:59 UTC by mohit-s96

closes #127 

- User of the Editor can now pass an `error` prop that will update the error state of the fixed editor.

2022-05-20 13:14 UTC, mohit-s96 commented
@AbhayVAshokan _a. Please review.

2022-05-20 15:37 UTC, AbhayVAshokan requested changes
@mohit-s96 _a please make the following changes and assign @karthiknmenon for the UI review.

https://vimeo.com/712110227/9aad5d97e8

2022-05-24 09:37 UTC, mohit-s96 commented
@karthiknmenon _a. Please review the UI changes. Let me know if the error message needs to be repositioned.

![neeto-editor-error-state](https://user-images.githubusercontent.com/17087942/169999679-f829cb1e-a9cf-4718-adb1-63e9223596d2.png)

2022-05-25 05:46 UTC, karthiknmenon requested changes
@mohit-s96 _a Please check. 
Also, please match the error styles with that of neetoUI Input Component.

2022-05-25 05:46 UTC, karthiknmenon commented on lib/components/Common/ErrorWrapper.jsx
> +import classNames from "classnames";
```suggestion
import classnames from "classnames";
```

2022-05-25 05:46 UTC, karthiknmenon commented on lib/components/Common/ErrorWrapper.jsx
> +    return <p className="ne-input__error">{message}</p>;
I would prefer just returning the error message from here and not the `p` element. 
Use the message in the `return` of this component.

2022-05-25 05:46 UTC, karthiknmenon commented on lib/components/Common/ErrorWrapper.jsx
> +    return <p className="ne-input__error">{message}</p>;
cc: @AbhayVAshokan

2022-05-26 08:31 UTC, mohit-s96 commented
@karthiknmenon _a. Please review. I compared the error message with neetoUI input and they both match.

2022-05-30 03:56 UTC, AbhayVAshokan commented
@karthiknmenon please provide an update on this PR. It has been open for quite some while now.

2022-05-31 05:04 UTC, karthiknmenon approved these changes

2022-05-31 05:04 UTC, merged