Add config files from wheel
neetozone/neeto-editor pull request #241
Opened 2022-05-20 13:08 UTC by mohit-s96

closes #233

2022-05-20 13:17 UTC, mohit-s96 commented
@AbhayVAshokan _a. Please review. There are many changes here, except a few config changes, almost all of them are styling/linting related.

2022-05-20 15:12 UTC, AbhayVAshokan requested changes
@mohit-s96 _a please check the changes.

2022-05-20 15:12 UTC, AbhayVAshokan commented on package.json
> +    "{src,example}/**/*.{js,jsx,json}": [
```suggestion
    "{lib,example}/**/*.{js,jsx,json}": [
```

2022-05-20 15:12 UTC, AbhayVAshokan commented on babel.config.js
> +};
It is better to restrict the babel config to what is required. If the `.babelrc` file is encountered during rebase (while resolving conflicts), please delete `.babelrc` and keep `babel.config.js` file.

```suggestion
module.exports = api => {
  api.cache(true);

  return {
    presets: ["@babel/preset-env", "@babel/preset-react"],
    plugins: ["@babel/plugin-proposal-class-properties"],
    env: {
      production: {
        plugins: [
          "@babel/plugin-proposal-class-properties",
          "@babel/plugin-transform-runtime",
        ],
      },
    },
  };
};

```

2022-05-24 09:36 UTC, mohit-s96 commented
@AbhayVAshokan _a. Please review the changes.

2022-05-24 10:01 UTC, AbhayVAshokan approved these changes
LGTM
@mohit-s96 _a please rebase with master to resolve all conflicts and proceed to merge.

2022-05-24 11:26 UTC, merged