Updated emoji mart package
neetozone/neeto-editor pull request #248
Opened 2022-05-30 13:40 UTC by mohit-s96

Updated the `emoji-mart` package to the latest version. The newest version had a lot of breaking changes. Also updated are the `webpack` related packages because the older versions were not working with the `emoji-mart` package.

## before the update

![before_update](https://user-images.githubusercontent.com/17087942/171003936-8ba00890-8b0b-450b-9671-62cdd7434ed8.png)

## after the update

![after_update](https://user-images.githubusercontent.com/17087942/171003911-2ffeb5ff-9dec-4cae-9e50-d53a48dd8f5d.png)

2022-05-30 13:47 UTC, mohit-s96 commented
@AbhayVAshokan _a. Please review.

2022-05-30 15:33 UTC, AbhayVAshokan requested changes
@mohit-s96 _a please have a look at the changes. Also please apply these suggestions as well: https://vimeo.com/715270840/7e1b6f2fb1

2022-05-30 15:33 UTC, AbhayVAshokan commented on lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/ExtensionConfig.js
> +            .insertContent(`${emoji?.native || emoji?.skins[0]?.native || ""} `)
I understand that `emoji.native` is no longer valid. Replace it with
```suggestion
            .insertContent(`${emoji?.skins[0]?.native || ""} `)
```

2022-06-01 10:32 UTC, karthiknmenon commented
@AbhayVAshokan _a Please take this up.

2022-06-01 15:04 UTC, AbhayVAshokan commented
@labeebklatif _a please have a look.

2022-06-06 09:26 UTC, labeebklatif commented
@AbhayVAshokan _a Please have a look at this [video](https://www.loom.com/share/e2a03c06c3e04de4ae6f05695d4fceb4)

2022-06-06 13:10 UTC, merged