Added PR template and publish action
neetozone/neeto-editor pull request #286
Opened 2022-07-19 13:18 UTC by AbhayVAshokan

Fixes #285 

- Added PR template.
- Synced CHANGELOG.md file with neetoUI.
- Synced `.github/workflows/publish.yml` workflows with neetoUI.

@amaldinesh7 _a please have a look. The PR template mentions about adding necessary labels. This practice has not been followed in neetoEditor. Hence, do check if the necessary changes for the same are added. I am not sure what the functionality of `enforce-label.yml` file is, so haven't added the same.

2022-07-19 15:50 UTC, amaldinesh7 requested changes
@AbhayVAshokan Please check the comments.

2022-07-19 15:50 UTC, amaldinesh7 commented on CHANGELOG.md
> +** Represent a component name in italics, eg: _Modal_.
Remove this

2022-07-19 15:50 UTC, amaldinesh7 commented on CHANGELOG.md
> +** Enclose a prop name in double backticks, eg: `isLoading`.
change the `isLoading` prop to some prop in neetoEditor. Do the same in PR template file as well.

2022-07-19 15:50 UTC, amaldinesh7 commented on .github/pull_request_template.md
> +Example:
Remove this for now.

2022-07-19 15:51 UTC, amaldinesh7 commented
I've created the necessary labels. The logic of enforce-label is it will add `skip-ci` label if the changes in the PR need not be published. For example if a PR only have changes to update documentation, we don't have to publish a new version.

2022-07-20 04:43 UTC, AbhayVAshokan commented
@amaldinesh7 _a

2022-07-20 16:40 UTC, amaldinesh7 approved these changes

2022-07-20 16:40 UTC, merged