Updated the UI to the new design system
neetozone/neeto-editor pull request #364
Opened 2022-09-21 11:24 UTC by goutham-subramanyam

Fixes #343

2022-09-25 22:44 UTC, goutham-subramanyam commented
@karthiknmenon _a Please check and merge.

cc: @AbhayVAshokan

2022-09-26 05:24 UTC, karthiknmenon requested changes
@goutham-subramanyam _a Please make the minor changes as discussed over call.

2022-09-26 05:24 UTC, karthiknmenon commented on lib/components/Common/Avatar.jsx
>  const SIZE = {
Can we move this along with all other constants to a constant file?

2022-09-26 07:23 UTC, AbhayVAshokan reviewed
The `yarn build` command is failing. @goutham-subramanyam _a can you please make this change at:
https://github.com/bigbinary/neeto-editor/blob/77d5098e9141e51bad09c158650ab9b138653e57/rollup.config.js#L46
```diff
-       commonjs()
+       commonjs({ include: /\**node_modules\**/ })
```

Also, once done, can you please commit the output of the `yarn build` command? This would generate the updated `editor-content.min.css` file which would be served to the changelog widget via neetoEditor CDN.

PS: This change is directly taken from [neetoUI#rollupConfig](https://github.com/bigbinary/neeto-ui/blob/e58a6fe859646d959ce160156b3a6d7726e554cb/rollup.config.js#L38).

2022-09-26 13:02 UTC, goutham-subramanyam commented
@karthiknmenon _a Made the suggested changes. Please check.

cc: @AbhayVAshokan

2022-09-26 13:07 UTC, karthiknmenon approved these changes
LGTM.

@AbhayVAshokan _a Please confirm and merge.

2022-09-26 13:13 UTC, AbhayVAshokan commented
<img width="581" alt="Screenshot 2022-09-26 at 6 41 14 PM" src="https://user-images.githubusercontent.com/35297280/192285310-eccc414f-070c-4540-9f49-ff3a9db7de47.png">

<img width="581" alt="Screenshot 2022-09-26 at 6 41 28 PM" src="https://user-images.githubusercontent.com/35297280/192285325-f8c435cd-654f-42c0-afcd-4e4600d7f0d3.png">

@goutham-subramanyam I am not a big fan of large buttons. I was curious to know if large buttons are indeed the right choice for these small modals.

2022-09-26 19:53 UTC, goutham-subramanyam commented
@AbhayVAshokan I had missed that. I have updated the buttons.

2022-09-27 02:34 UTC, AbhayVAshokan approved these changes
LGTM ❤️

2022-09-27 02:34 UTC, merged