Image enhancements
neetozone/neeto-editor pull request #456
Opened 2022-11-24 02:41 UTC by AbhayVAshokan

Fixes #408 

**Description**

**Checklist**

- [x] ~I have made corresponding changes to the documentation.~
- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

2022-11-24 03:36 UTC, AbhayVAshokan commented
https://vimeo.com/774534217/d8f526ca20

2022-11-24 04:03 UTC, karthiknmenon commented
cc: @goutham-subramanyam

2022-11-24 04:27 UTC, AbhayVAshokan commented
@karthiknmenon _a can you please do the first review?

**NOTE**
- The video upload feature will be the next to be worked on via https://github.com/bigbinary/neeto-editor/issues/452.
- The image UI components will be reused for video. The classes will be renamed accordingly as well.

2022-11-25 08:53 UTC, goutham-subramanyam reviewed
@AbhayVAshokan _a Please check the comments.

2022-11-25 08:53 UTC, goutham-subramanyam commented on lib/styles/editor/_editor-content.scss
> +    font-weight: normal;
```suggestion
    font-size: var(--neeto-ui-text-sm);
    font-weight: var(--neeto-ui-font-normal);
```

2022-11-25 08:53 UTC, goutham-subramanyam commented on lib/components/Editor/CustomExtensions/Image/ImageComponent.jsx
> +    <Dropdown
Instead of having a primary button for the dropdown, please use the secondary button.

2022-11-25 08:53 UTC, goutham-subramanyam commented on lib/styles/editor/_menu.scss
> +    right: 0;
Instead of placing it at the extreme corner, a little offset would be better. Try `2px` or `4px`.

2022-11-25 08:58 UTC, karthiknmenon requested changes

2022-11-25 08:58 UTC, karthiknmenon commented on lib/components/Editor/CustomExtensions/Image/ImageComponent.jsx
> +};
I would personally keep this as a separate file.

2022-11-25 10:26 UTC, AbhayVAshokan commented
@goutham-subramanyam the secondary button doesn't stand out as much as the primary button. I have made the suggested change. Personally, I prefer the primary button, or neeto-ui-text-gray-900.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/35297280/203958683-5303158f-fa19-4251-80c3-337ff82ee3f7.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/35297280/203958982-d7e58faf-8476-4740-93cf-3dd73d311e4e.png">

2022-11-25 11:22 UTC, goutham-subramanyam commented
> @goutham-subramanyam the secondary button doesn't stand out as much as the primary button. I have made the suggested change. Personally, I prefer the primary button, or neeto-ui-gray-900. WDYT?
> 

@AbhayVAshokan Should it stand out as much as a primary action?

<img width="1209" alt="Screenshot 2022-11-25 at 4 49 40 PM" src="https://user-images.githubusercontent.com/24496302/203974715-566ce3b6-c0e6-4f54-93bb-1e7ffffb3252.png">

In the screenshot above, the dropdown button stands out as much as the Submit button and it doesn't feel right. That's why I suggested updating it to a secondary button. If it's harder to differentiate from the image, we can add a shadow to the button so that it stands out from the image.

2022-11-25 12:18 UTC, AbhayVAshokan commented
@goutham-subramanyam you are right. The primary button might stand out a bit too much. Let's go forward with the secondary button for now. We can have style overrides if the need arises.

2022-11-25 12:18 UTC, merged