Add fuzzy search for mentions
neetozone/neeto-editor pull request #507
Opened 2022-12-28 07:45 UTC by gaagul

Fixes #470 

-  Used Fuse.js to implement the fuzzy search logic for mentions.

2022-12-28 10:01 UTC, AbhayVAshokan requested changes
@gaagul _a while making the PR don't remove the default content provided by the PR template. You need to update the default content.

2022-12-28 12:55 UTC, gaagul commented
@AbhayVAshokan Please Review.

2022-12-28 17:55 UTC, AbhayVAshokan commented on lib/components/Editor/CustomExtensions/Mention/utils.js
> +  };
I used the fuzzy mentions feature for a seed data of 5000 users.

1. The behaviour for low threshold is what is expected. Add a `threshold` of `0.25`.
2. The current logic impacts the performance greatly. Slice the resulting array to 10 items or below.

@gaagul _a

2022-12-29 04:01 UTC, leeoniya commented on lib/components/Editor/CustomExtensions/Mention/utils.js
> +  };
Fuse is quite slow and produces poor matches. you might consider something else:

https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

2022-12-29 04:16 UTC, AbhayVAshokan commented on lib/components/Editor/CustomExtensions/Mention/utils.js
> +  };
@leeoniya thank you for the suggestion. We'll definitely check out uFuzzy. For now we'll go forward with Fuse.js. We'll come back after creating a POC with uFuzzy and verifying the performance.

2022-12-29 06:10 UTC, gaagul commented
@AbhayVAshokan Please review.

2022-12-29 06:13 UTC, AbhayVAshokan commented on lib/components/Editor/CustomExtensions/Mention/utils.js
> +      return mentions;
```suggestion
      return mentions.slice(0, 10);
```

@gaagul _a merge after making this minor change.

2022-12-29 06:13 UTC, AbhayVAshokan approved these changes

2022-12-29 06:32 UTC, merged