Added video-embed option to the Menu
neetozone/neeto-editor pull request #586
Opened 2023-01-30 10:19 UTC by gaagul

Fixes #565 

**Description**

- Changed: video embed UI to show a Modal instead of an alert.
- Added: video embed option to the menu.

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

2023-01-30 10:41 UTC, gaagul commented
@gaagul _a

2023-01-30 10:42 UTC, gaagul commented
@AbhayVAshokan _a

2023-01-30 12:30 UTC, AbhayVAshokan requested changes
@gaagul _a

2023-01-30 12:30 UTC, AbhayVAshokan commented on lib/components/Editor/EmbedOption/index.jsx
> +          error={error ? "Please enter a valid URL" : null}
```suggestion
          error={error && "Please enter a valid URL" }
```

2023-01-31 04:12 UTC, gaagul commented
@AbhayVAshokan _a Please review the changes.

2023-01-31 04:30 UTC, AbhayVAshokan approved these changes
Nicely done 👌

2023-01-31 04:31 UTC, merged