Added support for emojis
neetozone/neeto-editor pull request #64
Opened 2021-12-01 03:56 UTC by AbhayVAshokan

Fixes #30 
- Upgraded `neeto-icons` package to version 1.8.13 to obtain the `Smiley` icon.
- Installed `emoji-mart` package for emoji picker.
- Added `Add emoji` option to slash commands. It opens an emoji picker tooltip using `tippy.js`.

Please go through the video: https://www.loom.com/share/9aa262a256274dfda340220079b09c6a

cc: @karthiknmenon, @labeebklatif

2021-12-02 10:09 UTC, labeebklatif commented
@AbhayVAshokan I think, the easiest method to show the emoji-picker at the selected node would be to add the decorator node as you did by using extension. May be we can change the key from ## to something else appropriate or to completely remove that, we will need to show the picker somewhere else. Will need to check if there are any alternate way to do this. 

@amaldinesh7 @karthiknmenon  Please share thoughts on this

2021-12-03 11:14 UTC, amaldinesh7 commented
@AbhayVAshokan _a How about colon as the decorator?

cc: @karthiknmenon

2021-12-03 13:02 UTC, AbhayVAshokan commented
@amaldinesh7 I have a few suggestions for the emoji picker feature. Please go through this video: https://vimeo.com/652867483/8ce3740a58

cc: @karthiknmenon

2021-12-03 13:47 UTC, amaldinesh7 commented
> @amaldinesh7 I have a few suggestions for the emoji picker feature. Please go through this video: https://vimeo.com/652867483/8ce3740a58
> 
> cc: @karthiknmenon

This looks good. Please push the changes. let me test it.

2021-12-03 16:52 UTC, AbhayVAshokan commented
New changes:
![Bubble Menu Emoji Picker](https://user-images.githubusercontent.com/35297280/144641215-b4e858d3-a438-426a-a3e3-1f8c21598acf.gif)

2021-12-06 07:38 UTC, AbhayVAshokan commented
@amaldinesh7 _a the PR is ready for review. Please take a look and suggest changes.

2021-12-06 18:28 UTC, amaldinesh7 commented
@AbhayVAshokan _a Please take a look at the video https://vimeo.com/653795736/bf20e31fe7. I've mentioned a few suggestions and while I am testing few bugs popped up. Create separate issues if you need. Fix the major ones here itself.

cc: @karthiknmenon @labeebklatif

2021-12-07 17:37 UTC, AbhayVAshokan commented
@amaldinesh7 _a please have a look at this video. I have made all the changes and fixed the bugs. I have raised one concern related to the slash menu as a separate issue (#81). I shall be working on it next.
video: https://vimeo.com/654195354/5799b04bca

cc: @karthiknmenon

2021-12-08 08:11 UTC, amaldinesh7 requested changes
@AbhayVAshokan _a Few minor suggestions. Please take a look.

2021-12-08 08:11 UTC, amaldinesh7 commented on lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/EmojiSuggestionMenu.js
> +class EmojiSuggestionMenu extends React.Component {
Can't we change this to a functional component?

2021-12-08 08:11 UTC, amaldinesh7 commented on lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
> +                      .insertContent("!")
instead of `!` can we use `::` to trigger the whole emoji picker. Thoughts?

2021-12-08 12:12 UTC, AbhayVAshokan commented
@amaldinesh7 _a please take a look through this video https://vimeo.com/654493245/fffbd3328a regarding the second review.

2021-12-08 19:20 UTC, amaldinesh7 commented
Please create a separate issue for adding the emoji option to the fixed header. It's good to have the emoji picker in fixed menu. @AbhayVAshokan

2021-12-08 19:20 UTC, merged