Integrated DynamicVariables from neeto-molecules
neetozone/neeto-editor pull request #680
Opened 2023-03-13 07:36 UTC by gaagul

- Fixes #679 

**Description**

- Replaced: custom implementation of `DynamicVariables` using neeto-molecules

**Checklist**

- [x] I have made corresponding changes to the documentation.
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

2023-03-13 12:52 UTC, AbhayVAshokan requested changes
- [ ] Add a tooltip for the Variables button.
- [ ] The button size should be "small".

@gaagul _a

2023-03-13 12:52 UTC, AbhayVAshokan commented on package.json
> +    "@bigbinary/neeto-molecules": "latest",
We should not add it to peer dependency before it added to `package-common.json` file. We'll make this change once that is done.

2023-03-13 13:44 UTC, AbhayVAshokan commented
@gaagul here is one additional change: https://vimeo.com/807511994/50142c0417

2023-03-14 05:35 UTC, gaagul commented
@AbhayVAshokan _a Please verify the changes to the styling.

2023-03-14 06:59 UTC, AbhayVAshokan requested changes
@gaagul _a one more change: https://vimeo.com/807809112/3085c03e7f

2023-03-14 09:30 UTC, gaagul commented
@AbhayVAshokan Please verify the new changes.

2023-03-14 10:34 UTC, AbhayVAshokan approved these changes

2023-03-14 10:35 UTC, merged