Fixed images not uploading after drag and drop
neetozone/neeto-editor pull request #737
Opened 2023-04-10 06:13 UTC by gaagul

- Fixes #736 

**Description**

- Fixed: images not being uploaded automatically after dropping into dropzone

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

2023-04-10 15:26 UTC, AbhayVAshokan requested changes
@gaagul _a https://vimeo.com/816244738/197742f45f

2023-04-10 15:50 UTC, gaagul commented
> @gaagul _a https://vimeo.com/816244738/197742f45f

@AbhayVAshokan _a This is specific to chromium based browsers similar to the issue we encountered while working on attachments.

2023-04-11 02:14 UTC, AbhayVAshokan commented
Understood. This issue is specific to the development mode. Merging.

2023-04-11 02:14 UTC, AbhayVAshokan approved these changes

2023-04-11 02:14 UTC, merged