Added preview for attachments
neetozone/neeto-editor pull request #748
Opened 2023-04-18 17:03 UTC by gaagul

- Fixes #740 

**Description**

- Added: preview for attachments

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

2023-04-19 04:42 UTC, gaagul commented
@AbhayVAshokan _a Please review.

2023-04-19 10:34 UTC, AbhayVAshokan requested changes
@gaagul_a 
Also check: https://vimeo.com/819069679/69662f01fd?share=copy

2023-04-19 10:34 UTC, AbhayVAshokan commented on src/components/Attachments/PreviewModal.jsx
> +import { Download, LeftArrow, RightArrow } from "neetoicons";
```suggestion
import { Download, Left, Right } from "neetoicons";
```

`Left` and `Right` icons have better aesthetics.

2023-04-20 02:31 UTC, AbhayVAshokan approved these changes
Nice work 👌. Please merge after making this change.

2023-04-20 02:31 UTC, AbhayVAshokan commented on src/components/Attachments/Attachment.jsx
> +              className="ne-attachments__attachment__preview-wrapper"
```suggestion
              className="ne-attachments__preview-wrapper"
```

This class name should be good enough. Make similar changes to the sub classes.

2023-04-20 04:20 UTC, merged