Made ammendments to code-block ui and language selection
neetozone/neeto-editor pull request #829
Opened 2023-07-12 09:17 UTC by gaagul

- Fixes #827 

**Description**

- Fixed: styling of code-block
- Added: "plaintext" as default
- Fixed: issues with parsed coodeblock in EditorContent

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

2023-07-13 12:51 UTC, AbhayVAshokan requested changes
@gaagul _a

2023-07-13 12:51 UTC, AbhayVAshokan commented on src/components/Editor/CustomExtensions/CodeBlock/CodeBlockComponent.jsx
> +  }, []);
https://vimeo.com/844942928/16b5819463

2023-07-13 13:14 UTC, gaagul commented
@AbhayVAshokan _a Please review the new changes.

2023-07-13 14:19 UTC, AbhayVAshokan requested changes
@gaagul _a we need strategy="fixed" for the dropdown so that the dropdown is visible:
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/407d6760-ac1d-4fda-b3bc-a94ff14c3378)

Currently this is cut off within the boundaries of the codeblock.

2023-07-14 05:09 UTC, gaagul commented
@AbhayVAshokan _a Please take a look at the updated  Ui, I have reverted the changes to dropdown strategy.

2023-07-16 13:00 UTC, AbhayVAshokan approved these changes
@gaagul _a please merge yourselves after this change.

2023-07-16 13:00 UTC, AbhayVAshokan commented on src/components/Editor/CustomExtensions/CodeBlock/CodeBlockComponent.jsx
- [ ] Remove `closeOnOutsideClick={false}` from the dropdown component. It is not user friendly.
- [ ] Remove auto from the list of available languages.
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/aad10c24-27cf-4523-91cf-5a48f47d3c89)

2023-07-16 16:42 UTC, merged