Add markdown editor
neetozone/neeto-editor pull request #97
Opened 2021-12-13 17:02 UTC by AbhayVAshokan

Fixes #28 
- Added markdown editor.
- Updated documentation.
- Uses [marked](https://www.npmjs.com/package/marked) package for markdown to HTML conversion.
- Uses [turndown](https://www.npmjs.com/package/turndown) package for HTML to markdown conversion.

Please go through this video: https://vimeo.com/656211314/5713fc4066

@amaldinesh7 _a please have a look.

2021-12-20 15:08 UTC, AbhayVAshokan commented
@amaldinesh7 _a the PR is ready for review.
New changes: https://vimeo.com/658620411/e5e9c7dc92

2021-12-20 19:44 UTC, amaldinesh7 commented
@labeebklatif _a Please take a look at this PR

2021-12-22 10:43 UTC, AbhayVAshokan commented
Rebased with master to resolve conflicts, it automatically fixed the minor slash commands bug mentioned in the video.

2021-12-23 11:58 UTC, labeebklatif commented
@AbhayVAshokan Please have a look at this: https://www.loom.com/share/fdf1461408924dc59ba56feb007857ab

2021-12-23 12:45 UTC, labeebklatif commented
@AbhayVAshokan _a assign back once the issues in the video are addressed

2021-12-24 06:24 UTC, yedhink commented
@AbhayVAshokan About adding line break in markdown:
- https://markdown-guide.readthedocs.io/en/latest/basics.html#line-return
- https://stackoverflow.com/questions/33191744/how-to-add-new-line-in-markdown-presentation

cc: @labeebklatif

2021-12-27 06:04 UTC, labeebklatif commented
> @AbhayVAshokan About adding line break in markdown:
> 
> * https://markdown-guide.readthedocs.io/en/latest/basics.html#line-return
> * https://stackoverflow.com/questions/33191744/how-to-add-new-line-in-markdown-presentation
> 
> cc: @labeebklatif

@yedhink Right. We realized markdown needs special syntax to indicate line breaks. But still, the issue exists when we add line breaks in Rich Text mode which is not reflected in the markdown because the line breaks are indicated as empty `p` tags rather than `br` tag in the editor content. @AbhayVAshokan is looking in to this.

2021-12-27 06:25 UTC, labeebklatif requested changes
@AbhayVAshokan _a Added some comments. Please go through them.

2021-12-27 06:25 UTC, labeebklatif commented on lib/components/Editor/CustomExtensions/Markdown/TabSwitcher.js
> +const MarkdownTabSwitcher = ({ isMarkdownTab, setIsMarkdownTab }) => {
```suggestion
const MarkdownTabSwitcher = ({ isMarkdownTabActive, setIsMarkdownTabActive }) => {
```

2021-12-27 06:25 UTC, labeebklatif commented on lib/components/Editor/index.js
> +  const [isMarkdownTab, setIsMarkdownTab] = useState(false);
```suggestion
  const [isMarkdownTabActive, setIsMarkdownTabActive] = useState(false);
```

2021-12-27 06:25 UTC, labeebklatif commented on lib/components/Editor/CustomExtensions/Markdown/index.js
> +      textareaRef.current.scrollHeight + 2 * BORDER_HEIGHT + "px";
Please check if this auto adjusting height can be achieved by css min-height as we have done for the Rich Text editor part.

2021-12-27 10:53 UTC, AbhayVAshokan commented
@labeebklatif _a take a look at the changes.
Fixed the link dropdown issue in #107, rebased with the latest master.
![Markdown linebreak](https://user-images.githubusercontent.com/35297280/147464684-d689cb3c-7975-4593-b92a-a5630ac1ee31.gif)

2021-12-27 12:19 UTC, labeebklatif approved these changes
LGTM!!

2021-12-27 12:19 UTC, merged